# Generated by Django 4.0.5 on 2022-06-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sobre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='sobre',
            field=models.CharField(max_length=10000),
        ),
    ]
