# Generated by Django 4.0.5 on 2022-06-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sobre_sobre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sobre',
        ),
    ]
