# Generated by Django 4.0.5 on 2022-06-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_sobre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('twiiter', models.CharField(max_length=100, verbose_name='Twitter')),
                ('facebook', models.CharField(max_length=100, verbose_name='Facebook')),
                ('youtube', models.CharField(max_length=100, verbose_name='Youtube')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Sociais',
            },
        ),
    ]
