# Generated by Django 4.0.5 on 2022-06-23 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='twiiter',
            new_name='twitter',
        ),
    ]
